---
stages:
  - build
  - test
  - deploy

build-app:
  stage : build
  script:
    - echo "Hello build"

unit-test:
  stage : test
  script :
    - echo "Hello unit-test"

curl-test:
  stage : test
  script : echo "Hello curl-test"

deploy-app :
  stage : deploy
  script : echo "Hello deploy-app"
