---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    - echo "Hello build"
    - touch testDB.db
    - sqlite3 testDB.db < mkdb.txt
    - echo "SELECT * FROM properties;" > sql.txt
    - sqlite3 testDB.db < sql.txt
    - rm testDB.db sql.txt

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"

curl-test:
  stage: curl_test
  script: echo "Hello curl-test"

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
