---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    - touch testDB.db
    - sqlite3 testDB.db < mkdb.txt

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"

curl-test:
  stage: curl_test
  script: 
    - python3 main.py -p 12188 &
    - servicePID=$!
    - echo "Replace with test_driver.sh localhost 12188"
    - kill -9 $servicePID

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
