---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    #- pip install --user Flask
    #- pip install --user flask-cors
    #- pip install --user flask-swagger-ui
    - pip list
    - touch testDB.db
    - sqlite3 testDB.db < mkdb.txt

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"

curl-test:
  stage: curl_test
  script: 
    - echo "Hello curl-test"

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
