---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    - echo "init stages"

unit-test:
  stage: unit_test
  script:
    - cd tests/unit_tests/
    - chmod u+x test_suite.sh
    - ./test_suite.sh

curl-test:
  stage: curl_test
  script: 
    - cd tests/curl_tests/
    - chmod u+x test_driver.sh
    - touch properties.db
    - sqlite3 properties.db < ../../mkdb.txt
    - python3 ../../src/main.py -p 12185 &> junk.txt &
    - ./test_driver.sh localhost 12185 $!

deploy-app:
  stage: deploy
  script:
    - echo "Deploying service"
    - echo "$MY_KEY" > key.txt
    - chmod 600 key.txt
