---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    - echo "init stage"

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"

curl-test:
  stage: curl_test
  script: 
    - cd tests/curl_tests/
    - chmod u+x test_driver.sh
    - touch properties.db
    - sqlite3 properties.db < ../../mkdb.txt
    - python3 ../../main.py -p 65003 &
    - ./test_driver.sh localhost 65003 $!

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
