---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    #- pip install --user Flask
    #- pip install --user flask-cors
    #- pip install --user flask-swagger-ui
    - touch testDB.db
    - sqlite3 testDB.db < mkdb.txt

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"
    - python3 -p 12186 main.py &
    - servic_epid=$!
    - echo service_pid
    - kill -9 service_pid

curl-test:
  stage: curl_test
  script: 
    - echo "Hello curl-test"

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
