---
stages:
  - unit_test
  - curl_test
  - deploy

unit-test:
  stage: unit_test
  script:
    - echo 'Skipping...'

curl-test:
  stage: curl_test
  script: 
    - echo 'Skipping...'

deploy-app:
  stage: deploy
  script:
    - echo 'Deploying to azure k8s'
    - az login --service-principal -u $APP_ID -p $PW --tenant $TENANT
    - az aks get-credentials --resource-group cs4783ResourceGroup --name cs4783Cluster
    - az acr login --name cs4783registry
    - az logout
