---
stages:
  - init
  - unit_test
  - curl_test
  - deploy

init-test:
  stage: init
  script:
    - echo "init stage"

unit-test:
  stage: unit_test
  script:
    - echo "Hello unit-test"

curl-test:
  stage: curl_test
  script: 
    - touch properties.db
    - sqlite3 properties.db < mkdb.txt
    - echo "curl test"
    #- cd tests/curl_tests/
    #- python3 ../../main.py -p 12190 &
    #- bash test_driver.sh localhost 12190

deploy-app:
  stage: deploy
  script: echo "Hello deploy-app"
