apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ddd233-db
  name: ddd233-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ddd233-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ddd233-db
    spec:
      containers:
      - image: cs4783registry.azurecr.io/ddd233-db:latest
        imagePullPolicy: ""
        name: ddd233-db
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
