version: '3'
services:
  db:
    build: ./sql-scripts/
    restart: always
    environment:
      - MYSQL_DATABASE=flask-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33006:3306"
    container_name: db
    hostname: db

  web-api:
    build: .
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=flask-db
      - MYSQL_HOST=localhost
      - BITNAMI_DEBUG=true
    
    depends_on:
      - "db"
    network_mode: host
    container_name: web-api
    hostname: web-api